### ISSUE TITLE
Cleanup .toc

### ISSUE THREAD

**Issue by Road-block** [cralor/TourGuide_Professions#3]
```
## Interface: 11200

## Title: TourGuide_Professions
## Notes: Professions guides for 1-300
## Author: cralor
## Version: Alpha
## X-Category: Professions

## RequiredDeps: TourGuideVanilla

Guides.xml
```
Plugin doesn't do anything different if Dongle or TomTom is present, that's the main addon (and Dongle dependency has been removed from that).  
There's also no reason to start it in a disabled state on fresh installations or have entries for addon loaders that didn't exist in vanilla.

**Comment by cralor** [comment]
Thanks. Overlooked these!
